// Chapter 9: Error Handling

mod panicking;
mod recoverable_with_result;

fn main() {
    // panicking::run();
    recoverable_with_result::run();
}
